name: Docker Build and Run

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the code
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up Docker Buildx (enables advanced build features)
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    # Step 3: Cache Docker layers (optional, helps speed up builds)
    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    # Step 4: Build Docker image
    - name: Build Docker image
      run: |
        docker build --no-cache -t random-forest-api .

    # Step 5: Run Docker container
    - name: Run Docker container
      run: |
        docker run -d -p 5000:5000 random-forest-api
