name: Docker Build and Test

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code from repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Step 3: Log in to DockerHub (if you're pushing to DockerHub)
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 4: Build Docker image
      - name: Build Docker image
        run: |
          docker build -f ./Dockerfile --no-cache -t random-forest-api .

      # Step 5: Run Docker container
      - name: Run Docker container
        run: |
          docker run -d -p 5000:5000 --name random-forest-api random-forest-api

      # Step 6: List running containers (for debugging)
      - name: List running containers
        run: docker ps

      # Step 7: View container logs (for debugging)
      - name: View container logs
        run: docker logs random-forest-api

      # Step 8: Test Flask API
      - name: Sleep before API test
        run: sleep 30  # Increase sleep time to ensure the container starts
      - name: Test API Endpoint
        run: |
          curl -X POST http://localhost:5000/predict -H "Content-Type: application/json" -d '{"features": [5.1, 3.5, 1.4, 0.2]}'
